### ISSUE TITLE
00 -- This is Heavy -- Donny Davis

### ISSUE THREAD

**Issue by donnywdavis** [TIYRaleigh/2016--April--iOS#2]
### Tasks:
- [X] [Create a Github account](https://github.com/signup)
- [X] Find and star [the class project](https://github.com/TIYRaleigh/2016--April--iOS)
- [x] Read [the Home page on the class wiki](https://github.com/TIYRaleigh/2016--April--iOS/wiki)
- [x] [Create a new _WIP Issue_](https://github.com/TIYRaleigh/2016--April--iOS/issues/new)
  - [x] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [x] With this checklist as the description
- [x] [Edit your Github profile](https://github.com/settings/profile) to provide:
  - [x] A picture, so I can recognize your face.
  - [x] Your full name, so I can recognize your name.
  - [x] A valid public email address, so I can contact you if I need to.
- [x] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  - [x] Add a link to your new Github repo as a comment on your _WIP Issue_
- [x] Complete the Code School course [Try Git](https://www.codeschool.com/courses/try-git)
  - [x] Take a screenshot of the Try Git course when you complete it and add it as a comment to your _WIP Issue_
- [x] Create a new repository called `TIY-Assignments`
  - [x] Check the box to create an initial `README.md` file
  - [x] Select the `CC0` -- "Creative Commons" license for your work
  - [x] Add a link to your `TIY-Assignments` repo as a comment on your _WIP Issue_
- [x] Install Xcode from the Mac App Store. Simply search for _Xcode_.
- [x] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3, will probably be 9.0 when class starts). Once fully downloaded, the docset should have a small checkmark next to it.
- [x] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
  - [x] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
  - [x] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
- [x] Complete the [Swift Basics](http://teamtreehouse.com/library/swift-basics) course on Treehouse.
  - [x] Take a screenshot of your points earned for the course and add it as a comment to your _WIP Issue_
- [x] Look at the Prework-A file for instructions on how to complete the Counter app.
  - [x] Your counter app files should be added to your TIY-Assignments repo. Because you previously added a link to your repo to your _WIP Issue_, I will be able to see your progress as you go. Be sure to commit/push the changes you make as you work on the app.
- [x] Read and complete the exercises for the [Command Line Crash Course](http://cli.learncodethehardway.org/book/). The command line is another name for the terminal. There are about 20 commands you'll use all the time on the command line, and it's helpful to have them memorized so we can use them right away.

**Comment by donnywdavis** [comment]
[Hello World Repo](https://github.com/donnywdavis/hello-world)

**Comment by donnywdavis** [comment]
![try_git](https://cloud.githubusercontent.com/assets/2036378/14060775/2b7a6598-f345-11e5-82ac-d95097ea0202.png)

**Comment by donnywdavis** [comment]
[TIY-Assignments Repo](https://github.com/donnywdavis/TIY-Assignments)

**Comment by donnywdavis** [comment]
Swift Basics Treehouse course.

![treehouse_points](https://cloud.githubusercontent.com/assets/2036378/14108783/cb666a72-f58c-11e5-84a8-e534d2a3ed56.png)

**Comment by donnywdavis** [comment]
## Prework-A Counter App

### Steps to Success

#### Storyboard Tasks
- [x] Click the small yellow/orange circular button at the top of the view. This will select the view controller as the active object.
- [x] Click the rightmost of the three buttons in the upper right corner of the Xcode window to open the inspector pane.
- [x] Once the inspector is open, click on the _connections inspector_ tab (it is the small circle with an arrow).
- [x] Under Outlets, you should see names like _countTextField_, _slider_, and _stepper_. Go to the CounterViewController.swift file and look at the top of the file under the line `class CounterViewController`. You should see properties with the same names. Go back to the storyboard and click and drag from the empty circle next to these names to their appropriate UI element in the storyboard view. You are _wiring up_ your interface elements to their corresponding properties in code. This allows you to manipulate them in code. Once you connect these outlets to the UI elements in the view, the empty circles should fill in. You can also then hover your mouse over the outlet in the list and the associated element will be highlighted in the view.
- [x] In the same tab (the connections inspector), there is another section labelled, _received actions_. There should be three names listed. Each of them are methods in the code that will run certain instructions. We need to connect them to the appropriate UI elements so when certain actions are taken by the user, these methods will be triggered. For _sliderValueChanged:_ and _stepperValueChanged:_, simply drag from the empty circles to the appropriate UI element in the view. When you let go of the mouse over the element, several event types will appear. Take a guess which one to use.
- [x] The third item under _received actions_ is called _viewTapped:_. This is a method that will cause the keyboard to hide in the case where the user has tapped the textfield and edited the value. We need to connect it to something called a _gesture recognizer_. It does what you'd expect; it recognizes gestures. I've already set up a tap gesture recognizer that will fire whenever the main view is tapped. To wire it up to our method _viewTapped:_, simply drag from the empty circle to the top of our view where the four little icons are. The third icon from the left (the small grey square with a blue circle in the corner) is our gesture recognizer. Drag the line from the empty circle to this icon. It will blink and then the circle next to _viewTapped:_ will be filled in.

Everything in our storyboard view is now properly wired up to the appropriate variables/methods in our code! When UI elements are touched by our user, the code in our view controller will be invoked.

#### Code Tasks

The following steps are numbered. You will find corresponding comments in the CounterViewController.swift file with the same numbers.
- [x] 1. Here you are _calling a method_. A method is a collection of instructions that are executed together. Anything listed in CounterViewController with the keyword `func` in front of it is a method . Read the comment and try to figure out which method we should call here (the method exists somewhere in the file).
- [x] 2. What variable from the top of the class should we use to update the textfield?
- [x] 3. What value should the slider show?
- [x] 4. And the stepper (detecting a pattern here)?
- [x] 5.  What property of sender should we use (Big hint in the comment for this one)?
- [x] 6. What method should we call here? 
- [x] 7. This looks suspiciously similar. What goes in these blanks?
- [x] 8. After we hide the keyboard and update the currentCount variable, what should we do?
