### ISSUE TITLE
00 -- This is Heavy -- Steve Graff

### ISSUE THREAD

**Issue by slgraff** [TIYRaleigh/2016--April--iOS#4]
### Tasks:
- [X] [Create a Github account](https://github.com/signup)
- [X] Find and star [the class project](https://github.com/TIYRaleigh/2016--April--iOS)
- [x] Read [the Home page on the class wiki](https://github.com/TIYRaleigh/2016--April--iOS/wiki)
- [x] [Create a new _WIP Issue_](https://github.com/TIYRaleigh/2016--April--iOS/issues/new)
  - [x] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [x] With this checklist as the description
- [x] [Edit your Github profile](https://github.com/settings/profile) to provide:
  - [x] A picture, so I can recognize your face.
  - [x] Your full name, so I can recognize your name.
  - [x] A valid public email address, so I can contact you if I need to.
- [x] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  - [x] Add a link to your new Github repo as a comment on your _WIP Issue_
- [x] Complete the Code School course [Try Git](https://www.codeschool.com/courses/try-git)
  - [x] Take a screenshot of the Try Git course when you complete it and add it as a comment to your _WIP Issue_
- [x] Create a new repository called `TIY-Assignments`
  - [x] Check the box to create an initial `README.md` file
  - [x] Select the `CC0` -- "Creative Commons" license for your work
  - [x] Add a link to your `TIY-Assignments` repo as a comment on your _WIP Issue_
- [x] Install Xcode from the Mac App Store. Simply search for _Xcode_.
- [x] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3, will probably be 9.0 when class starts). Once fully downloaded, the docset should have a small checkmark next to it.
- [x] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
  - [x] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
  - [x] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
- [x] Complete the [Swift Basics](http://teamtreehouse.com/library/swift-basics) course on Treehouse.
  - [x] Take a screenshot of your points earned for the course and add it as a comment to your _WIP Issue_
- [x] Look at the Prework-A file for instructions on how to complete the Counter app.
  - [x] Your counter app files should be added to your TIY-Assignments repo. Because you previously added a link to your repo to your _WIP Issue_, I will be able to see your progress as you go. Be sure to commit/push the changes you make as you work on the app.
- [x] Read and complete the exercises for the [Command Line Crash Course](http://cli.learncodethehardway.org/book/). The command line is another name for the terminal. There are about 20 commands you'll use all the time on the command line, and it's helpful to have them memorized so we can use them right away.

**Comment by slgraff** [comment]
[TIY-Assignments](https://github.com/slgraff/TIY-Assignments)

**Comment by slgraff** [comment]
[GitHub 'hello-world' repo](https://github.com/slgraff/hello-world)

**Comment by slgraff** [comment]
Completed 'Try Git' course on Code School.
![try git](https://cloud.githubusercontent.com/assets/12915136/14131092/fa0ca606-f605-11e5-8add-6f9e41473190.png)

**Comment by slgraff** [comment]
Completed Swift Basics course on Treehouse.

![screen shot 2016-04-02 at 11 52 28 am](https://cloud.githubusercontent.com/assets/12915136/14227367/b7f11e0c-f8c9-11e5-99a8-727da6ab337f.png)

![screen shot 2016-04-02 at 11 53 30 am](https://cloud.githubusercontent.com/assets/12915136/14227373/c63bf022-f8c9-11e5-99ed-80f867b92a3b.png)

**Comment by slgraff** [comment]
Completed the Counter app assignment, but changes were pushed to my fork of the entire [2016--April-iOS repository here](https://github.com/slgraff/2016--April--iOS). Made a copy of the Counter projects in Finder and submitted that to GitHub, so it won't show commit history.
